const boardStyles=document.createElement('link');boardStyles.rel='stylesheet';boardStyles.href='./boards.css';document.head.appendChild(boardStyles);
const $=s=>document.querySelector(s),landing=$('#landing'),workspace=$('#workspace'),grid=$('#feedGrid'),editor=$('#editor'),platforms=$('#platforms');
let platform='',boardId='',editIndex=-1,imageData='';
let data={blog:[],instagram:[],youtube:[]};
const meta={blog:['BLOG FEED','블로그','사진을 카드형 3열 피드로 미리 배치해 보세요.','B'],instagram:['INSTAGRAM GRID','Instagram','세로형 3:4 게시물을 실제 피드처럼 배열해 보세요.','◎'],youtube:['YOUTUBE TITLES','YouTube','검은 썸네일과 제목을 구성하고 촬영 메모를 남겨보세요.','▶']};

let dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('feed-planner-db',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('state'))req.result.createObjectStore('state')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
async function loadData(){let migrated=false;try{const db=await dbPromise;const saved=await new Promise((resolve,reject)=>{const tx=db.transaction('state','readonly'),r=tx.objectStore('state').get('planner');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(saved)data=saved;else{const old=localStorage.getItem('feed-planner-v1');if(old)data=JSON.parse(old)}}catch(e){const old=localStorage.getItem('feed-planner-v1');if(old)data=JSON.parse(old)}for(const p of Object.keys(meta)){const entries=Array.isArray(data[p])?data[p]:[],alreadyBoards=entries.length>0&&entries.every(entry=>entry&&typeof entry==='object'&&Array.isArray(entry.items)&&'id'in entry&&'name'in entry);if(!alreadyBoards){data[p]=[{id:'default',name:meta[p][1],items:entries}];migrated=true}}if(migrated)await persist();renderLanding();if(platform&&currentBoard())render()}
async function persist(){try{const db=await dbPromise;await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(data,'planner');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});localStorage.setItem('feed-planner-v1-meta',JSON.stringify({updated:Date.now()}))}catch(e){alert('저장하지 못했습니다. Safari의 개인정보 보호 모드가 아닌지 확인해 주세요.')}}
if(navigator.storage&&navigator.storage.persist)navigator.storage.persist().catch(()=>{});const ready=loadData();

function currentBoard(){return(data[platform]||[]).find(board=>board.id===boardId)}
function renderLanding(){platforms.innerHTML='';for(const p of Object.keys(meta)){const group=document.createElement('section');group.className='platform-group';group.innerHTML=`<div class="platform-group-head"><h3>${esc(meta[p][1])}</h3><button class="account-add" data-create="${p}">＋ 계정 추가</button></div><div class="board-list"></div>`;const list=group.querySelector('.board-list');data[p].forEach(board=>{const card=document.createElement('div');card.className=`platform ${p}`;card.innerHTML=`<button class="platform-main"><b>${meta[p][3]}</b><span><strong>${esc(board.name)}</strong><small>게시물 ${board.items.length}개</small></span><i>→</i></button>`;card.querySelector('button').onclick=()=>openBoard(p,board.id);list.appendChild(card)});group.querySelector('[data-create]').onclick=()=>createBoard(p);platforms.appendChild(group)}}
function makeId(){return globalThis.crypto&&crypto.randomUUID?crypto.randomUUID():`board-${Date.now()}-${Math.random().toString(36).slice(2)}`}
async function createBoard(p){const suggestion=`${meta[p][1]} ${data[p].length+1}`,entered=prompt('새 피드 보드 이름을 입력해 주세요.',suggestion);if(entered===null)return;const board={id:makeId(),name:entered.trim()||suggestion,items:[]};data[p].push(board);await persist();renderLanding();openBoard(p,board.id)}
function openBoard(p,id){const board=(data[p]||[]).find(entry=>entry.id===id);if(!board)return;platform=p;boardId=id;landing.hidden=true;workspace.hidden=false;$('#homeBtn').hidden=false;$('#clearBtn').hidden=false;$('#platformLabel').textContent=meta[p][0];$('#workspaceTitle').textContent=board.name;$('#workspaceDesc').textContent=meta[p][2];grid.className='feed-grid '+p;render()}
$('#homeBtn').onclick=()=>{workspace.hidden=true;landing.hidden=false;$('#homeBtn').hidden=true;$('#clearBtn').hidden=true;platform='';boardId='';renderLanding()};
function render(){const board=currentBoard();if(!board)return;grid.innerHTML='';board.items.forEach((item,i)=>{const c=document.createElement('article');c.className='feed-card';if(platform==='youtube')c.innerHTML=`<div class="thumb">THUMBNAIL</div><div class="yt-copy"><h3>${esc(item.title)||'제목을 입력해 주세요'}</h3><p>${esc(item.memo)||'썸네일을 눌러 촬영 메모 작성'}</p></div>${tools(i)}`;else c.innerHTML=`${item.image?`<img src="${item.image}" alt="피드 이미지">`:`<div class="placeholder">${esc(item.title)||'새 게시물'}</div>`}${tools(i)}`;const opener=c.querySelector('.thumb,.yt-copy,img,.placeholder');if(opener)opener.onclick=()=>openEditor(i);c.querySelectorAll('[data-act]').forEach(b=>b.onclick=e=>{e.stopPropagation();act(b.dataset.act,i)});grid.appendChild(c)});if(!board.items.length)grid.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:80px 20px;color:#aaa">아래 ＋ 버튼을 눌러 첫 콘텐츠를 추가하세요.</div>'}
function tools(i){return `<div class="card-tools"><button data-act="up">↑</button><button data-act="down">↓</button><button data-act="delete">×</button></div>`}
async function act(a,i){const items=currentBoard().items;if(a==='delete')items.splice(i,1);else{let n=a==='up'?i-1:i+1;if(n>=0&&n<items.length)[items[i],items[n]]=[items[n],items[i]]}await persist();render()}
function openEditor(i=-1){editIndex=i;let item=i>=0?currentBoard().items[i]:{title:'',memo:'',image:''};$('#editorTitle').textContent=i>=0?'콘텐츠 수정':'콘텐츠 추가';$('#titleInput').value=item.title||'';$('#memoInput').value=item.memo||'';imageData=item.image||'';$('#deleteBtn').hidden=i<0;$('#imageField').hidden=platform==='youtube';drawPreview();editor.hidden=false}
$('#addBtn').onclick=()=>openEditor();$('#closeEditor').onclick=()=>editor.hidden=true;editor.onclick=e=>{if(e.target===editor)editor.hidden=true};
function drawPreview(){$('#imagePreview').innerHTML=imageData?`<img src="${imageData}" alt="선택한 사진">`:'<span>＋</span><p>사진 선택</p>'}
$('#imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(im.width,im.height)),cv=document.createElement('canvas');cv.width=Math.round(im.width*scale);cv.height=Math.round(im.height*scale);cv.getContext('2d').drawImage(im,0,0,cv.width,cv.height);imageData=cv.toDataURL('image/jpeg',.82);drawPreview()};im.src=r.result};r.readAsDataURL(f)};
$('#saveBtn').onclick=async()=>{let item={title:$('#titleInput').value.trim(),memo:$('#memoInput').value.trim(),image:imageData},items=currentBoard().items;if(editIndex>=0)items[editIndex]=item;else items.push(item);await persist();editor.hidden=true;render()};
$('#deleteBtn').onclick=async()=>{if(editIndex>=0)currentBoard().items.splice(editIndex,1);await persist();editor.hidden=true;render()};
$('#clearBtn').onclick=async()=>{const board=currentBoard();if(board&&confirm(`${board.name} 콘텐츠를 모두 지울까요?`)){board.items=[];await persist();render();renderLanding()}};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(reg=>{reg.update();reg.addEventListener('updatefound',()=>{})}).catch(()=>{});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()})}

// Best-effort daily backup to the home server: silently skipped when the PC is off, retried next time the app opens.
async function dailyBackup(){try{const today=new Date().toISOString().slice(0,10);if(localStorage.getItem('feed-backup-date')===today)return;await ready;const res=await fetch('https://appointee-unnoticed-donated.ngrok-free.dev/api/app-backup/feed',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(res.ok)localStorage.setItem('feed-backup-date',today)}catch(e){}}
setTimeout(dailyBackup,3000);
