const $=s=>document.querySelector(s),landing=$('#landing'),workspace=$('#workspace'),grid=$('#feedGrid'),editor=$('#editor');
let platform='',editIndex=-1,imageData='';
let data={blog:[],instagram:[],youtube:[]};
const meta={blog:['BLOG FEED','Blog','사진을 카드형 3열 피드로 미리 배치해 보세요.'],instagram:['INSTAGRAM GRID','Instagram','세로형 3:4 게시물을 실제 피드처럼 배열해 보세요.'],youtube:['YOUTUBE TITLES','YouTube','검은 썸네일과 제목을 구성하고 촬영 메모를 남겨보세요.']};

let dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('feed-planner-db',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('state'))req.result.createObjectStore('state')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
async function loadData(){try{const db=await dbPromise;const saved=await new Promise((resolve,reject)=>{const tx=db.transaction('state','readonly'),r=tx.objectStore('state').get('planner');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(saved)data=saved;else{const old=localStorage.getItem('feed-planner-v1');if(old){data=JSON.parse(old);await persist()}}}catch(e){const old=localStorage.getItem('feed-planner-v1');if(old)data=JSON.parse(old)}if(platform)render()}
async function persist(){try{const db=await dbPromise;await new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(data,'planner');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});localStorage.setItem('feed-planner-v1-meta',JSON.stringify({updated:Date.now()}))}catch(e){alert('저장하지 못했습니다. Safari의 개인정보 보호 모드가 아닌지 확인해 주세요.')}}
if(navigator.storage&&navigator.storage.persist)navigator.storage.persist().catch(()=>{});loadData();

function openPlatform(p){platform=p;landing.hidden=true;workspace.hidden=false;$('#homeBtn').hidden=false;$('#clearBtn').hidden=false;$('#platformLabel').textContent=meta[p][0];$('#workspaceTitle').textContent=meta[p][1];$('#workspaceDesc').textContent=meta[p][2];grid.className='feed-grid '+p;render()}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPlatform(b.dataset.open));$('#homeBtn').onclick=()=>{workspace.hidden=true;landing.hidden=false;$('#homeBtn').hidden=true;$('#clearBtn').hidden=true};
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();openPlatform(b.dataset.add);openEditor()});
function render(){grid.innerHTML='';data[platform].forEach((item,i)=>{const c=document.createElement('article');c.className='feed-card';if(platform==='youtube')c.innerHTML=`<div class="thumb">THUMBNAIL</div><div class="yt-copy"><h3>${esc(item.title)||'제목을 입력해 주세요'}</h3><p>${esc(item.memo)||'썸네일을 눌러 촬영 메모 작성'}</p></div>${tools(i)}`;else c.innerHTML=`${item.image?`<img src="${item.image}" alt="피드 이미지">`:`<div class="placeholder">${esc(item.title)||'새 게시물'}</div>`}${tools(i)}`;const opener=c.querySelector('.thumb,.yt-copy,img,.placeholder');if(opener)opener.onclick=()=>openEditor(i);c.querySelectorAll('[data-act]').forEach(b=>b.onclick=e=>{e.stopPropagation();act(b.dataset.act,i)});grid.appendChild(c)});if(!data[platform].length)grid.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:80px 20px;color:#aaa">아래 ＋ 버튼을 눌러 첫 콘텐츠를 추가하세요.</div>'}
function tools(i){return `<div class="card-tools"><button data-act="up">↑</button><button data-act="down">↓</button><button data-act="delete">×</button></div>`}
async function act(a,i){if(a==='delete')data[platform].splice(i,1);else{let n=a==='up'?i-1:i+1;if(n>=0&&n<data[platform].length)[data[platform][i],data[platform][n]]=[data[platform][n],data[platform][i]]}await persist();render()}
function openEditor(i=-1){editIndex=i;let item=i>=0?data[platform][i]:{title:'',memo:'',image:''};$('#editorTitle').textContent=i>=0?'콘텐츠 수정':'콘텐츠 추가';$('#titleInput').value=item.title||'';$('#memoInput').value=item.memo||'';imageData=item.image||'';$('#deleteBtn').hidden=i<0;$('#imageField').hidden=platform==='youtube';drawPreview();editor.hidden=false}
$('#addBtn').onclick=()=>openEditor();$('#closeEditor').onclick=()=>editor.hidden=true;editor.onclick=e=>{if(e.target===editor)editor.hidden=true};
function drawPreview(){$('#imagePreview').innerHTML=imageData?`<img src="${imageData}" alt="선택한 사진">`:'<span>＋</span><p>사진 선택</p>'}
$('#imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(im.width,im.height)),cv=document.createElement('canvas');cv.width=Math.round(im.width*scale);cv.height=Math.round(im.height*scale);cv.getContext('2d').drawImage(im,0,0,cv.width,cv.height);imageData=cv.toDataURL('image/jpeg',.82);drawPreview()};im.src=r.result};r.readAsDataURL(f)};
$('#saveBtn').onclick=async()=>{let item={title:$('#titleInput').value.trim(),memo:$('#memoInput').value.trim(),image:imageData};if(editIndex>=0)data[platform][editIndex]=item;else data[platform].push(item);await persist();editor.hidden=true;render()};
$('#deleteBtn').onclick=async()=>{if(editIndex>=0)data[platform].splice(editIndex,1);await persist();editor.hidden=true;render()};
$('#clearBtn').onclick=async()=>{if(confirm(`${meta[platform][1]} 콘텐츠를 모두 지울까요?`)){data[platform]=[];await persist();render()}};
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});

// Best-effort daily backup to the home server: silently skipped when the PC is off, retried next time the app opens.
async function dailyBackup(){try{const today=new Date().toISOString().slice(0,10);if(localStorage.getItem('feed-backup-date')===today)return;await loadData();const res=await fetch('https://appointee-unnoticed-donated.ngrok-free.dev/api/app-backup/feed',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(res.ok)localStorage.setItem('feed-backup-date',today)}catch(e){}}
setTimeout(dailyBackup,3000);
